version: '3.7'
services:
  db:
    image: postgres:12.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
  web:
    image: phathdt379/eshop:1.0
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/eshop
      SECRET_KEY_BASE: 43HToczwEtbLIujVyC/L7syuUDAEHklOVydWoxt6Tu33IfUGT8ZaQbpVTcH5jnw8
      SECRET_JOKEN: 43HToczwEtbLIujVyC/L7syuUDAEHklOVydWoxt6Tu33IfUGT8ZaQbpVTcH5jnw8
    ports:
      - 4000:4000
